export const PROVINCES = [
  { id: 1, name: "Hà Nội" },
  { id: 2, name: "TP Hồ Chí Minh" },
  { id: 3, name: "Hải Phòng" },
  { id: 4, name: "Đà Nẵng" },
  { id: 5, name: "Cần Thơ" },
  { id: 6, name: "Huế" },
  { id: 7, name: "An Giang" },
  { id: 8, name: "Bắc Ninh" },
  { id: 9, name: "Cà Mau" },
  { id: 10, name: "Đắk Lắk" },
  { id: 11, name: "Đồng Nai" },
  { id: 12, name: "Đồng Tháp" },
  { id: 13, name: "Gia Lai" },
  { id: 14, name: "Hưng Yên" },
  { id: 15, name: "Khánh Hòa" },
  { id: 16, name: "Lào Cai" },
  { id: 17, name: "Lâm Đồng" },
  { id: 18, name: "Ninh Bình" },
  { id: 19, name: "Phú Thọ" },
  { id: 20, name: "Quảng Ngãi" },
  { id: 21, name: "Quảng Trị" },
  { id: 22, name: "Tây Ninh" },
  { id: 23, name: "Thái Nguyên" },
  { id: 24, name: "Tuyên Quang" },
  { id: 25, name: "Vĩnh Long" },
  { id: 26, name: "Thanh Hóa" },
  { id: 27, name: "Nghệ An" },
  { id: 28, name: "Hà Tĩnh" },
  { id: 29, name: "Quảng Ninh" },
  { id: 30, name: "Lạng Sơn" },
  { id: 31, name: "Cao Bằng" },
  { id: 32, name: "Sơn La" },
  { id: 33, name: "Điện Biên" },
  { id: 34, name: "Lai Châu" },
];
